name: Actualizador de Tasas BCV

on:
  schedule:
    # Corre cada 5 min de 4:00 PM a 6:59 PM (Hora Vzla) de Lunes a Viernes
    # 20-22 UTC = 16-18 VZLA | 1-5 = Lunes a Viernes
    - cron: '*/5 20-22 * * 1-5'
    
    # Corre a las 3:45 PM (Hora Vzla) para preparar la transición
    - cron: '45 19 * * 1-5'

  workflow_dispatch: # Mantiene el botón verde activo
jobs:
  actualizar-data:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v2

      - name: Instalar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instalar Librerías
        run: pip install requests firebase-admin beautifulsoup4
    
      - name: Run Script
        run: python BcvEuroapp.py
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Guardar cambios en el repo
        run: |
          git config --global user.name 'Robot'
          git config --global user.email 'robot@github.com'
          git add Bcveuro.json Bcveuro_proxima.json Bcveuro_vigente.json
          git commit -m "Tasas actualizadas: General, Proxima y Vigente" || exit 0
          git pull --rebase origin main
          git push
